plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

sourceSets {
	elements {
		java {
			srcDirs = ['src/elements/java']
		}
		resources {
			srcDirs = ['src/elements/resources']
		}
	}
}

sourceSets.elements.compileClasspath += sourceSets.main.output + sourceSets.main.compileClasspath

loom {
	mods {
		"arcane-artistry" {
			sourceSet sourceSets.main
			sourceSet sourceSets.elements
		}
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	runtimeOnly sourceSets.elements.output
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

sourcesJar {
	from sourceSets.elements.allSource
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}

	from sourceSets.elements.output
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

tasks.register('cleanRunClient') {
    group = 'fabric'
    description = 'Cleans build artifacts and launches the Minecraft client.'
    dependsOn tasks.clean, tasks.runClient
}

tasks.named('runClient') {
    mustRunAfter tasks.clean
}
