# ---------------------------------------------------------------------------
# Minecraft & toolchain
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.160.0+26.2
loom_version=1.17.17

# Java
java_version=25

# ---------------------------------------------------------------------------
# Mod metadata
mod_version=0.0.0
maven_group=net.arcaneartistry
