pluginManagement {
  repositories {
    maven {
      name = 'Fabric'
      url = 'https://maven.fabricmc.net/' }
    gradlePluginPortal()
  }
}

rootProject.name = 'arcane-artistry'

include 'arcane-artistry-core'
include 'arcane-artistry-base'
include 'arcane-artistry'
// include 'arcane-artistry-alchemy'
