name: Bug report
title: "[BUG]"
labels: Bug
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug. Make sure Arcane Artistry is the **only** mod enabled.
            value: |
                1.
                2.
                3.
                ...
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Expected Result
            description: A clear and concise description of what you expected to happen
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem.
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report or Log
            description: If applicable, please add a **link** to the crash report or log that was created when this issue occured. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue.
        validations:
            required: false
    -   type: dropdown
        attributes:
            label: Mod Version
            description: The [mod version - minecraft version] you were using when the bug occured
            options:
                - "0.0.1 - 1.20.4"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Additional Context
            description: Add any extra context about the bug here
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking your time and helping improve Arcane Artistry!"
